# Generated by Django 5.2.13 on 2026-04-25 06:51

import apps.accounts.managers.user_manager
import apps.accounts.models._uuid
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

# Auto-update trigger per docs/01_architecture/data-model.md.
CREATE_SET_UPDATED_AT_FN = """
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;
"""

DROP_SET_UPDATED_AT_FN = "DROP FUNCTION IF EXISTS set_updated_at();"

CREATE_USER_ACCOUNTS_TRIGGER = """
DROP TRIGGER IF EXISTS set_user_accounts_updated_at ON user_accounts;
CREATE TRIGGER set_user_accounts_updated_at
BEFORE UPDATE ON user_accounts
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
"""

DROP_USER_ACCOUNTS_TRIGGER = (
    "DROP TRIGGER IF EXISTS set_user_accounts_updated_at ON user_accounts;"
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=apps.accounts.models._uuid.uuid_v7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Lowercased, unique. The login identifier.', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='False blocks authentication; soft-delete also flips this.')),
                ('is_staff', models.BooleanField(default=False, help_text='Grants access to the Django admin.')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant scope — nullable today; required once the Account model lands and existing rows have been backfilled.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_deleted', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_updated', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user_accounts',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('email',), name='uq_user_accounts_email_active')],
            },
            managers=[
                ('objects', apps.accounts.managers.user_manager.UserManager()),
            ],
        ),
        migrations.RunSQL(
            sql=CREATE_SET_UPDATED_AT_FN,
            reverse_sql=DROP_SET_UPDATED_AT_FN,
        ),
        migrations.RunSQL(
            sql=CREATE_USER_ACCOUNTS_TRIGGER,
            reverse_sql=DROP_USER_ACCOUNTS_TRIGGER,
        ),
    ]
