# Generated by Django 5.2.13 on 2026-04-25 16:54

import apps.accounts.models._uuid
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFARecoveryCode',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models._uuid.uuid_v7, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(help_text='SHA-256 hex digest of the plaintext code.', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('consumed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mfa_recovery_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'consumed_at'], name='ix_mfa_rc_user_consumed_at')],
                'constraints': [models.UniqueConstraint(fields=('user', 'code_hash'), name='uq_mfa_recovery_codes_user_code_hash')],
            },
        ),
    ]
