# Generated by Django 5.2.13 on 2026-04-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_tenant_fk_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp the user clicked the verification link. Null = unverified.', null=True),
        ),
    ]
