# Generated by Django 5.2.13 on 2026-04-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_backfill_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', help_text='Optional given name. Empty string when not set.', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Optional family name. Empty string when not set.', max_length=150),
        ),
    ]
