# Generated by Django 5.2.13 on 2026-04-26 02:05

import apps.accounts.models._uuid
import apps.accounts.models.invite
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The User who created this tenant. Nullable only during sign-up.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models._uuid.uuid_v7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Lowercased invitee address. Not unique across the table.', max_length=254)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hex digest of the plaintext token. Plaintext is never stored.', max_length=64)),
                ('expires_at', models.DateTimeField(default=apps.accounts.models.invite._default_expires_at)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invite_accepted', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invites_sent', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_revoked', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='invites', to='accounts.account')),
            ],
            options={
                'db_table': 'invites',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True), ('revoked_at__isnull', True)), fields=('tenant', 'email'), name='uq_invites_pending_tenant_email')],
            },
        ),
    ]
