# Generated by Django 5.2.13 on 2026-04-26 03:07

import apps.accounts.models._uuid
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_backfill_account_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models._uuid.uuid_v7, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(blank=True, default='', help_text="Snapshot of the actor's email at write time.", max_length=254)),
                ('action', models.CharField(db_index=True, help_text="Namespaced action code, e.g. 'auth.sign_in'.", max_length=64)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, default='', max_length=32)),
                ('target_label', models.CharField(blank=True, default='', help_text='Short human label captured at write time (e.g. invitee email).', max_length=254)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for system actions or after the actor is removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_as_actor', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='accounts.account')),
            ],
            options={
                'db_table': 'audit_events',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='ix_audit_tenant_recent')],
            },
        ),
    ]
