/**
 * Emit dist/tokens.css and dist/tokens.d.ts.
 *
 * Token data is duplicated below from src/primitive/ and src/semantic/ on
 * purpose: this script runs as plain Node ESM and can't import .ts modules.
 * If you change a token, update both the .ts source and the literal below
 * (a future iteration will fold these together via tsx or tsc-emit).
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const DIST = resolve(HERE, "dist");

const gray = {
  50: "#f9fafb", 100: "#f3f4f6", 200: "#e5e7eb", 300: "#d1d5db",
  400: "#9ca3af", 500: "#6b7280", 600: "#4b5563", 700: "#374151",
  800: "#1f2937", 900: "#111827", 950: "#030712",
};
const indigo = {
  50: "#eef2ff", 300: "#a5b4fc", 400: "#818cf8", 600: "#4f46e5",
  700: "#4338ca", 900: "#312e81",
};
const red = { 500: "#ef4444", 600: "#dc2626" };
const amber = { 500: "#f59e0b", 600: "#d97706" };
const green = { 500: "#22c55e", 600: "#16a34a" };
const white = "#ffffff";
const black = "#000000";

const lightSemantic = {
  "color-bg-canvas": gray[50],
  "color-bg-surface": white,
  "color-bg-overlay": "rgb(17 24 39 / 0.5)",
  "color-fg-default": gray[900],
  "color-fg-muted": gray[600],
  "color-fg-subtle": gray[500],
  "color-fg-on-accent": white,
  "color-border-subtle": gray[200],
  "color-border-default": gray[300],
  "color-border-emphasis": gray[400],
  "color-accent-fg": indigo[600],
  "color-accent-emphasis": indigo[700],
  "color-accent-bg-subtle": indigo[50],
  "color-success-fg": green[600],
  "color-warning-fg": amber[600],
  "color-danger-fg": red[600],
  "color-shadow-rgb": "0 0 0",
  "color-black": black,
};

const darkSemantic = {
  "color-bg-canvas": gray[950],
  "color-bg-surface": gray[900],
  "color-bg-overlay": "rgb(0 0 0 / 0.6)",
  "color-fg-default": gray[50],
  "color-fg-muted": gray[400],
  "color-fg-subtle": gray[500],
  "color-fg-on-accent": white,
  "color-border-subtle": gray[800],
  "color-border-default": gray[700],
  "color-border-emphasis": gray[600],
  "color-accent-fg": indigo[400],
  "color-accent-emphasis": indigo[300],
  "color-accent-bg-subtle": indigo[900],
  "color-success-fg": green[500],
  "color-warning-fg": amber[500],
  "color-danger-fg": red[500],
  "color-shadow-rgb": "0 0 0",
  "color-black": black,
};

const renderBlock = (selector, tokens) => {
  const lines = Object.entries(tokens).map(([key, value]) => `  --${key}: ${value};`);
  return `${selector} {\n${lines.join("\n")}\n}`;
};

const css = [
  "/* Generated by packages/tokens/build.mjs — do not edit directly. */",
  renderBlock(':root, [data-theme="light"]', lightSemantic),
  renderBlock('[data-theme="dark"]', darkSemantic),
  "",
].join("\n\n");

await mkdir(DIST, { recursive: true });
await writeFile(resolve(DIST, "tokens.css"), css, "utf8");

const dts = [
  "// Generated. Re-export of semantic token names for typed consumers.",
  "export type SemanticTokenName =",
  ...Object.keys(lightSemantic).map((k) => `  | "${k}"`),
  ";",
  "",
].join("\n");

await writeFile(resolve(DIST, "tokens.d.ts"), dts, "utf8");

console.log(`tokens: wrote ${resolve(DIST, "tokens.css")}`);
console.log(`tokens: wrote ${resolve(DIST, "tokens.d.ts")}`);
